
 

version: '3.3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: container-mongodb
    environment:
    - MONGO_DATA_DIR=./data/db
    - MONGO_LOG_DIR=./log
    ports:
      - "27017:27017"
    volumes:
      - ./data_mongodb/db:/data/db